In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np

In [8]:
o20 = pd.read_excel('file:///\\Fileserver01\d_drive\lvpcprojects\Pop%20+%20Emp%20Projections%202019\Feb%202019%20Update\TAZ%20based%20results\
/Final%20480%20TAZ%20result\SociaEconomic%20Data%20TAZ%20480.xlsx', sheet_name = '2020')

o25 = pd.read_excel('file:///\\Fileserver01\d_drive\lvpcprojects\Pop%20+%20Emp%20Projections%202019\Feb%202019%20Update\TAZ%20based%20results\
/Final%20480%20TAZ%20result\SociaEconomic%20Data%20TAZ%20480.xlsx', sheet_name = '2025')

o20.head()
o25.head()
o20.shape == o25.shape

,Zone,HH Population,GQPop,TotPop,HH,RetEmp,OffEmp,IndEmp,OthEmp,TotEmp,SchEnr,UniEnr,GAF
0,1,436.488488,0.0,436.488488,172.163172,15.872240,14.412071,119.718742,32.494620,182.497674,0,0,0
1,2,606.310936,0.0,606.310936,233.982548,20.953147,158.400600,33.431986,369.775955,582.561688,3910,0,0
2,3,251.664600,0.0,251.664600,92.324532,3.169166,17.818529,3.840933,5.217189,30.045818,0,0,0
3,4,295.119551,0.0,295.119551,116.600842,6.168816,6.495435,8.198079,8.300208,29.162538,0,0,0
4,5,1663.339151,0.0,1663.339151,636.692733,89.125259,294.687539,61.829584,211.350514,656.992896,1538,0,0

,Zone,HH Population,GQPop,TotPop,HH,RetEmp,OffEmp,IndEmp,OthEmp,TotEmp,SchEnr,UniEnr,GAF
0,1,491.215954,0.0,491.215954,194.320629,15.864086,14.441690,119.673136,34.783703,184.762615,0,0,0
1,2,628.853263,0.0,628.853263,243.908031,21.422643,160.897537,34.942179,375.556901,592.819261,3910,0,0
2,3,318.620417,0.0,318.620417,117.580871,3.167762,17.810630,3.839231,5.491018,30.308640,0,0,0
3,4,408.174153,0.0,408.174153,161.594969,6.161929,6.488184,8.188927,9.035043,29.874084,0,0,0
4,5,1745.148917,0.0,1745.148917,670.382308,89.125008,294.686711,61.829411,211.386301,657.027431,1538,0,0

True

In [10]:
#Add suffix to all the columns in each dataframe.

o20.columns = [str(col) + '_20' for col in o20.columns]
o25.columns = [str(col) + '_25' for col in o25.columns]
o20.head()

,Zone_20,HH Population_20,GQPop_20,TotPop_20,HH_20,RetEmp_20,OffEmp_20,IndEmp_20,OthEmp_20,TotEmp_20,SchEnr_20,UniEnr_20,GAF_20
0,1,436.488488,0.0,436.488488,172.163172,15.872240,14.412071,119.718742,32.494620,182.497674,0,0,0
1,2,606.310936,0.0,606.310936,233.982548,20.953147,158.400600,33.431986,369.775955,582.561688,3910,0,0
2,3,251.664600,0.0,251.664600,92.324532,3.169166,17.818529,3.840933,5.217189,30.045818,0,0,0
3,4,295.119551,0.0,295.119551,116.600842,6.168816,6.495435,8.198079,8.300208,29.162538,0,0,0
4,5,1663.339151,0.0,1663.339151,636.692733,89.125259,294.687539,61.829584,211.350514,656.992896,1538,0,0

In [16]:
o20.columns[np.r_[1, 3:(len(o25.columns) - 3)]]

Index(['HH Population_20', 'TotPop_20', 'HH_20', 'RetEmp_20', 'OffEmp_20',
       'IndEmp_20', 'OthEmp_20', 'TotEmp_20'],
      dtype='object')

In [26]:
df = pd.concat([o20, o25], axis=1)
df.columns
df.head()

Index(['Zone_20', 'HH Population_20', 'GQPop_20', 'TotPop_20', 'HH_20',
       'RetEmp_20', 'OffEmp_20', 'IndEmp_20', 'OthEmp_20', 'TotEmp_20',
       'SchEnr_20', 'UniEnr_20', 'GAF_20', 'Zone_25', 'HH Population_25',
       'GQPop_25', 'TotPop_25', 'HH_25', 'RetEmp_25', 'OffEmp_25', 'IndEmp_25',
       'OthEmp_25', 'TotEmp_25', 'SchEnr_25', 'UniEnr_25', 'GAF_25'],
      dtype='object')

,Zone_20,HH Population_20,GQPop_20,TotPop_20,HH_20,RetEmp_20,OffEmp_20,IndEmp_20,OthEmp_20,TotEmp_20,...,TotPop_25,HH_25,RetEmp_25,OffEmp_25,IndEmp_25,OthEmp_25,TotEmp_25,SchEnr_25,UniEnr_25,GAF_25
0,1,436.488488,0.0,436.488488,172.163172,15.872240,14.412071,119.718742,32.494620,182.497674,...,491.215954,194.320629,15.864086,14.441690,119.673136,34.783703,184.762615,0,0,0
1,2,606.310936,0.0,606.310936,233.982548,20.953147,158.400600,33.431986,369.775955,582.561688,...,628.853263,243.908031,21.422643,160.897537,34.942179,375.556901,592.819261,3910,0,0
2,3,251.664600,0.0,251.664600,92.324532,3.169166,17.818529,3.840933,5.217189,30.045818,...,318.620417,117.580871,3.167762,17.810630,3.839231,5.491018,30.308640,0,0,0
3,4,295.119551,0.0,295.119551,116.600842,6.168816,6.495435,8.198079,8.300208,29.162538,...,408.174153,161.594969,6.161929,6.488184,8.188927,9.035043,29.874084,0,0,0
4,5,1663.339151,0.0,1663.339151,636.692733,89.125259,294.687539,61.829584,211.350514,656.992896,...,1745.148917,670.382308,89.125008,294.686711,61.829411,211.386301,657.027431,1538,0,0

In [28]:
c1[0][:-3] + '_22'

'HH Population_22'

In [33]:
c1 = o20.columns[np.r_[1, 3:(len(o25.columns) - 3)]]
c2 = o25.columns[np.r_[1, 3:(len(o25.columns) - 3)]]
for x,y in zip(c1, c2):
    df[(x[:-3] + '_22')] = 0.6*df[x] + 0.4*df[y]

In [34]:
df

,Zone_20,HH Population_20,GQPop_20,TotPop_20,HH_20,RetEmp_20,OffEmp_20,IndEmp_20,OthEmp_20,TotEmp_20,...,UniEnr_25,GAF_25,HH Population_22,TotPop_22,HH_22,RetEmp_22,OffEmp_22,IndEmp_22,OthEmp_22,TotEmp_22
0,1,436.488488,0.000000,436.488488,172.163172,15.872240,14.412071,119.718742,32.494620,182.497674,...,0,0,458.379474,458.379474,181.026155,15.868979,14.423919,119.700500,33.410253,183.403650
1,2,606.310936,0.000000,606.310936,233.982548,20.953147,158.400600,33.431986,369.775955,582.561688,...,0,0,615.327867,615.327867,237.952741,21.140946,159.399375,34.036063,372.088334,586.664717
2,3,251.664600,0.000000,251.664600,92.324532,3.169166,17.818529,3.840933,5.217189,30.045818,...,0,0,278.446927,278.446927,102.427068,3.168604,17.815370,3.840252,5.326720,30.150947
3,4,295.119551,0.000000,295.119551,116.600842,6.168816,6.495435,8.198079,8.300208,29.162538,...,0,0,340.341392,340.341392,134.598493,6.166061,6.492534,8.194418,8.594142,29.447156
4,5,1663.339151,0.000000,1663.339151,636.692733,89.125259,294.687539,61.829584,211.350514,656.992896,...,0,0,1696.063058,1696.063058,650.168563,89.125158,294.687208,61.829515,211.364829,657.006710
5,6,27.825547,0.000000,27.825547,15.813718,182.673449,984.162418,145.769796,239.131797,1551.737460,...,0,0,28.206640,28.206640,16.026239,186.669615,991.011567,148.581462,248.310279,1574.572923
6,7,305.112576,0.000000,305.112576,245.090430,475.853368,831.759774,315.507563,164.522720,1787.643425,...,0,0,305.112576,305.112576,245.488951,484.171719,837.082369,315.745352,163.906327,1800.905767
7,8,494.544476,0.000000,494.544476,200.499216,612.556925,2286.406007,108.553245,202.229724,3209.745901,...,0,1,505.778470,505.778470,205.344642,615.987841,2297.843697,108.616611,202.101339,3224.549489
8,9,363.695099,0.000000,363.695099,158.692726,18.355475,31.880834,8.469151,11.942554,70.648013,...,0,0,373.811353,373.811353,163.331567,18.355361,31.880636,8.469099,11.951111,70.656207
9,10,890.837633,0.000000,890.837633,383.034089,17.778157,58.290413,36.557418,84.364657,196.990645,...,0,0,928.778903,928.778903,399.917065,18.096715,58.276649,36.548786,84.344035,197.266185
10,11,518.881738,0.000000,518.881738,233.854795,9.756234,25.975025,25.502050,11.330883,72.564192,...,0,0,576.218794,576.218794,260.066620,9.754483,25.970363,25.497473,11.599038,72.821357
11,12,1447.437161,216.840909,1664.278071,578.159046,741.781241,350.965426,35.855136,441.047588,1569.649391,...,0,0,1466.069126,1682.910035,585.924012,755.284905,350.562963,35.814020,437.816900,1579.478787
12,13,49.256026,3.218750,52.474776,19.674648,5.419992,190.346049,322.739179,246.426316,764.931536,...,0,0,49.616132,52.834882,19.829321,5.927794,204.972612,331.593902,277.342745,819.837054
13,14,333.207924,0.000000,333.207924,126.040689,160.675813,40.319138,4.991240,30.711218,236.697409,...,0,0,380.262433,380.262433,144.177105,164.166657,40.461927,4.982849,30.673837,240.285270
14,15,41.339317,0.000000,41.339317,17.162375,203.145976,438.359226,679.606662,572.571354,1893.683219,...,0,0,50.246451,50.246451,20.944689,203.990476,471.947708,699.935671,643.785408,2019.659262
15,16,1165.309585,0.000000,1165.309585,421.914659,190.443882,115.030061,144.021721,84.463225,533.958888,...,0,0,1170.623580,1170.623580,424.222777,204.072079,117.574773,144.508835,85.007041,551.162729
16,17,293.549470,0.000000,293.549470,96.141694,2.111158,9.576190,11.920079,7.646195,31.253622,...,0,0,306.869101,306.869101,100.585896,2.117710,9.841104,12.080294,8.273195,32.312303
17,18,666.970980,0.000000,666.970980,259.574319,42.586527,68.429105,43.163269,45.247082,199.425983,...,0,0,711.248599,711.248599,277.129909,43.594669,69.880855,44.038882,48.176929,205.691335
18,19,302.559413,0.000000,302.559413,113.500829,8.304159,10.114150,9.136798,8.488350,36.043457,...,0,0,348.335799,348.335799,130.844544,8.324411,10.110881,9.133846,8.667505,36.236642
19,20,2219.046648,0.000000,2219.046648,937.099117,333.625347,194.716971,169.963492,73.450575,771.756386,...,0,0,2234.503522,2234.503522,943.850815,334.720188,196.317606,170.032738,74.232085,775.302618
20,21,3764.031108,0.000000,3764.031108,1781.440912,427.547820,618.688133,183.180030,662.429539,1891.845522,...,0,0,3809.038033,3809.038033,1803.002323,430.109416,618.798991,183.107562,662.550490,1894.566460
21,22,1484.735988,0.000000,1484.735988,660.951672,117.130011,425.329464,574.270588,374.220767,1490.950829,...,0,0,1517.908027,1517.908027,676.172905,117.884515,444.817157,585.762245,414.364954,1562.828871
22,23,1195.485021,0.000000,1195.485021,463.376219,42.241931,64.596347,29.714139,41.667613,178.220030,...,0,0,1221.531664,1221.531664,473.747717,42.270235,65.357036,29.937213,42.470842,180.035326
23,24,1312.600867,0.000000,1312.600867,654.497742,69.015305,44.072966,15.178300,18.944828,147.211399,...,0,0,1330.586542,1330.586542,663.998750,74.009079,43.931850,15.129701,17.894087,150.964717
24,25,468.620323,0.000000,468.620323,212.945178,295.161570,319.429915,144.083219,167.368533,926.043237,...,0,0,498.870088,498.870088,226.737805,303.462340,319.056479,143.914776,165.554353,931.987948
25,26,2001.961758,0.000000,2001.961758,894.753572,54.139945,57.103038,48.637334,28.740950,188.621267,...,0,0,2045.501844,2045.501844,915.038691,54.138882,57.101917,48.636380,28.813665,188.690844
26,27,2940.130563,0.000000,2940.130563,1246.326152,113.876353,134.596630,82.698188,68.007600,399.178770,...,0,0,2994.879221,2994.879221,1269.967518,113.878834,134.596572,82.698527,68.158877,399.332811
27,28,4022.654707,0.000000,4022.654707,1608.765917,137.220238,186.647361,171.072234,126.839528,621.779362,...,0,0,4021.363399,4021.363399,1608.538374,137.634318,187.174912,171.548631,128.837735,625.195597
28,29,2241.416985,0.000000,2241.416985,858.323790,273.618924,115.311108,97.010100,86.895018,572.835149,...,0,0,2318.364205,2318.364205,887.754046,283.651286,117.699687,99.174018,98.081717,598.606709
29,30,54.127520,0.000000,54.127520,20.086212,79.969220,112.559993,284.095747,193.443229,670.068189,...,0,0,72.534290,72.534290,26.885046,90.171703,125.829705,296.009940,246.375005,758.386354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,451,946.410037,0.000000,946.410037,385.310944,14.654209,40.732456,27.538971,99.143119,182.068756,...,0,0,1036.631820,1036.631820,422.255626,14.651767,40.725667,27.534381,100.363195,183.275010
451,452,813.348932,0.000000,813.348932,306.090514,19.367396,44.718529,68.776862,12.754096,145.616883,...,0,0,843.467183,843.467183,317.674587,19.365609,44.714403,68.770517,13.284791,146.135320
452,453,799.008237,0.000000,799.008237,311.865420,58.862194,80.006940,252.213290,38.834016,429.916440,...,0,0,828.101223,828.101223,323.453866,59.126403,80.353111,252.574013,40.569593,432.623120
453,454,1896.176913,0.000000,1896.176913,645.060054,33.313197,87.257983,104.242036,78.560363,303.373580,...,0,0,1921.516906,1921.516906,654.097113,33.337129,87.289243,104.270460,79.051590,303.948422
454,455,2092.913395,0.000000,2092.913395,701.276289,105.803792,90.496862,81.516946,52.499795,330.317395,...,0,0,2159.122246,2159.122246,723.818301,109.826411,90.186957,81.237793,54.036889,335.288050
455,456,110.661760,0.000000,110.661760,48.802610,135.071518,154.284978,100.034721,85.083585,474.474802,...,0,0,113.222952,113.222952,49.874435,138.582378,158.836653,104.072532,102.286601,503.778163
456,457,1035.069063,0.000000,1035.069063,422.691092,23.949801,44.071595,26.175149,16.304188,110.500733,...,0,0,1048.440098,1048.440098,428.379603,23.949758,44.071515,26.175101,16.311859,110.508233
457,458,1080.790033,0.000000,1080.790033,453.303466,6.440815,1.890978,2.893513,4.495091,15.720396,...,0,0,1133.584332,1133.584332,475.675891,6.440696,1.890953,2.893467,4.507399,15.732515
458,459,17.000000,0.000000,17.000000,9.000000,177.106872,114.090465,86.496074,27.987770,405.681181,...,0,0,17.000000,17.000000,9.000000,178.759046,113.940104,86.382136,28.166897,407.248184
459,460,440.320353,0.000000,440.320353,185.678344,625.873061,396.548810,98.574193,131.176479,1252.172543,...,0,1,467.265837,467.265837,197.091687,630.005197,397.783513,98.499714,131.925613,1258.214036
460,461,799.992328,0.000000,799.992328,292.483293,41.963933,47.112436,58.182668,24.373568,171.632604,...,0,0,842.863083,842.863083,308.311754,42.869513,47.036677,58.089069,24.703386,172.698646
461,462,456.000000,0.000000,456.000000,252.000000,293.371139,576.540167,1713.342968,507.089443,3090.343716,...,0,0,456.000000,456.000000,252.000000,307.187427,593.731358,1730.489939,573.038826,3204.447550
462,463,1080.925536,0.000000,1080.925536,366.910115,7.224621,8.205825,2.766531,4.921801,23.118777,...,0,0,1070.341940,1070.341940,363.525006,7.224405,8.205580,2.766448,4.948354,23.144787
463,464,63.474678,0.000000,63.474678,27.054781,188.537125,129.237626,97.733415,87.977604,503.485770,...,0,0,63.051334,63.051334,26.843031,213.298177,144.556119,101.830115,110.474189,570.158601
464,465,299.897144,0.000000,299.897144,152.737562,26.424156,96.505750,52.136815,32.400441,207.467162,...,0,0,300.353902,300.353902,152.950224,26.424100,96.505545,52.136704,32.417232,207.483582
465,466,550.532327,0.000000,550.532327,196.978812,96.433211,77.353250,192.031107,45.525759,411.343328,...,0,0,553.892036,553.892036,198.040430,97.057765,77.310300,191.924484,47.091628,413.384177
466,467,471.548731,0.000000,471.548731,144.281444,358.108864,164.600925,40.849755,59.534602,623.094146,...,0,1,481.253011,481.253011,147.245649,364.575181,164.065154,40.716790,60.224824,629.581949
467,468,4194.374315,45.000000,4239.374315,1675.385653,109.484611,272.440238,45.944996,92.663436,520.533281,...,0,0,4344.540936,4389.540936,1736.354658,109.491170,273.171173,45.947748,94.763782,523.373874
468,469,37.000000,0.000000,37.000000,12.000000,0.932532,7.822049,0.239372,22.266892,31.260845,...,0,0,37.000000,37.000000,12.000000,0.932531,7.822047,0.239371,22.267304,31.261253
469,470,8.051614,0.000000,8.051614,3.958828,150.747314,58.133439,193.271032,42.521697,444.673482,...,0,0,8.085922,8.085922,3.959911,152.195113,59.863929,194.995224,49.178778,456.233044
470,471,626.218223,0.000000,626.218223,228.972274,99.966565,1101.323626,2703.914858,447.311366,4352.516416,...,0,0,635.959488,635.959488,232.566368,100.121652,1174.417139,2708.109676,460.293293,4442.941760
471,472,299.950141,0.000000,299.950141,125.460202,0.440019,6.574374,3.821424,1.328080,12.163898,...,0,0,348.566229,348.566229,145.786226,0.441038,7.293506,3.830276,1.519980,13.084800
472,473,308.560807,0.000000,308.560807,121.505733,8.186006,20.797450,34.162516,8.980218,72.126191,...,0,0,412.877456,412.877456,162.576866,8.185152,20.797782,34.158949,9.291156,72.433038
473,474,1900.187107,0.000000,1900.187107,873.909755,12.070099,50.040024,189.796675,45.802584,250.806364,...,0,0,2220.644093,2220.644093,1017.887956,12.755182,52.062352,190.330064,46.075063,257.576113
474,475,1013.516726,0.000000,1012.914906,404.622034,13.775259,131.489395,275.847175,18.268453,411.820001,...,0,0,1040.122346,1038.871609,415.476829,14.312521,131.632336,275.980556,18.253378,415.399033
475,476,579.152415,0.000000,578.808518,231.334539,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,594.355626,593.640919,237.540550,0.000000,0.000000,0.000000,0.000000,0.000000
476,477,1009.210366,0.000000,1009.210366,372.784067,136.985901,171.833145,44.364825,202.283408,552.574549,...,0,0,1045.393864,1045.393864,386.443429,144.502944,175.489650,45.091466,209.301498,570.048168
477,478,43.754559,0.000000,43.754559,23.249903,1017.815960,182.776129,227.162700,684.606066,2057.666172,...,0,0,43.951147,43.951147,23.388730,1035.072769,187.154245,229.773646,710.907130,2105.123529
478,479,10.695559,0.000000,10.695559,5.812476,0.000000,194.860501,242.511531,76.067341,523.741314,...,0,0,10.743614,10.743614,5.847183,0.000000,199.528079,245.298892,78.989681,535.820717
479,480,0.000000,0.000000,0.000000,0.000000,0.000000,292.290752,363.767296,76.067341,746.758758,...,0,0,0.000000,0.000000,0.000000,0.000000,299.292119,367.948338,78.989681,763.981764

In [35]:
df.columns

Index(['Zone_20', 'HH Population_20', 'GQPop_20', 'TotPop_20', 'HH_20',
       'RetEmp_20', 'OffEmp_20', 'IndEmp_20', 'OthEmp_20', 'TotEmp_20',
       'SchEnr_20', 'UniEnr_20', 'GAF_20', 'Zone_25', 'HH Population_25',
       'GQPop_25', 'TotPop_25', 'HH_25', 'RetEmp_25', 'OffEmp_25', 'IndEmp_25',
       'OthEmp_25', 'TotEmp_25', 'SchEnr_25', 'UniEnr_25', 'GAF_25',
       'HH Population_22', 'TotPop_22', 'HH_22', 'RetEmp_22', 'OffEmp_22',
       'IndEmp_22', 'OthEmp_22', 'TotEmp_22'],
      dtype='object')

In [54]:
for x,y in (enumerate(df.columns)):
    print(x, y)

0 Zone_20
1 HH Population_20
2 GQPop_20
3 TotPop_20
4 HH_20
5 RetEmp_20
6 OffEmp_20
7 IndEmp_20
8 OthEmp_20
9 TotEmp_20
10 SchEnr_20
11 UniEnr_20
12 GAF_20
13 Zone_25
14 HH Population_25
15 GQPop_25
16 TotPop_25
17 HH_25
18 RetEmp_25
19 OffEmp_25
20 IndEmp_25
21 OthEmp_25
22 TotEmp_25
23 SchEnr_25
24 UniEnr_25
25 GAF_25
26 HH Population_22
27 TotPop_22
28 HH_22
29 RetEmp_22
30 OffEmp_22
31 IndEmp_22
32 OthEmp_22
33 TotEmp_22

In [55]:
df1 = df[df.columns[np.r_[0, 2, 10:12, (len(df.columns)- 7):34]]]
df1.head()

,Zone_20,GQPop_20,SchEnr_20,UniEnr_20,TotPop_22,HH_22,RetEmp_22,OffEmp_22,IndEmp_22,OthEmp_22,TotEmp_22
0,1,0.0,0,0,458.379474,181.026155,15.868979,14.423919,119.700500,33.410253,183.403650
1,2,0.0,3910,0,615.327867,237.952741,21.140946,159.399375,34.036063,372.088334,586.664717
2,3,0.0,0,0,278.446927,102.427068,3.168604,17.815370,3.840252,5.326720,30.150947
3,4,0.0,0,0,340.341392,134.598493,6.166061,6.492534,8.194418,8.594142,29.447156
4,5,0.0,1538,0,1696.063058,650.168563,89.125158,294.687208,61.829515,211.364829,657.006710

In [56]:
df1.columns = [t[:-3] for t in df1.columns ]
df1.columns
df1.head()

Index(['Zone', 'GQPop', 'SchEnr', 'UniEnr', 'TotPop', 'HH', 'RetEmp', 'OffEmp',
       'IndEmp', 'OthEmp', 'TotEmp'],
      dtype='object')

,Zone,GQPop,SchEnr,UniEnr,TotPop,HH,RetEmp,OffEmp,IndEmp,OthEmp,TotEmp
0,1,0.0,0,0,458.379474,181.026155,15.868979,14.423919,119.700500,33.410253,183.403650
1,2,0.0,3910,0,615.327867,237.952741,21.140946,159.399375,34.036063,372.088334,586.664717
2,3,0.0,0,0,278.446927,102.427068,3.168604,17.815370,3.840252,5.326720,30.150947
3,4,0.0,0,0,340.341392,134.598493,6.166061,6.492534,8.194418,8.594142,29.447156
4,5,0.0,1538,0,1696.063058,650.168563,89.125158,294.687208,61.829515,211.364829,657.006710

In [57]:
writer = pd.ExcelWriter('H:\lvpcprojects\Pop + Emp Projections 2019\Feb 2019 Update\TAZ based results\InterpolationTwoYears\Interpolation22.xlsx')
df1.to_excel(writer, '2022')
writer.save()